### ISSUE TITLE
Unable to recognise encoding of this document at ...

### ISSUE THREAD

**Issue by bedna-KU** [bbidulock/xdg-traymenu#1]
Hi, where maybe issue?

xdg-menugen --verbose --root-menu /home/mario/.icewm/menu  --format icewm
    Root menu: /home/mario/.icewm/menu
    Format:    icewm
    Desktop:   ICEWM
    Theme:     gnome
    Charset:   UTF-8
    Language:  en_US.UTF-8
    Lang:      en_US
Unable to recognise encoding of this document at /usr/share/perl5/XML/SAX/PurePerl/EncodingDetect.pm line 100.
Document requires an element [Ln: 1, Col: 0]

**Comment by bbidulock** [comment]
So, is /home/mario/.icewm/menu the freedesktop.org DTD Menu 1.0 XML formatted input file?  I think that /home/mario/.icewm/menu should be the output file no?  Try:

```
xdg-menugen -v -o /home/mario/.icewm/menu
```

Note that the menu works better when you have [xdg-launch](/bbidulock/xdg-launch) installed (xdg-menugen uses it to launch applications with full startup notification).

**Comment by bedna-KU** [comment]
Command

```
xdg-menugen -v -o /home/mario/.icewm/menu
```

throws this error

```
missing root menu
```

**Comment by ghost** [comment]
any further updates regarding this issue ?

**Comment by bedna-KU** [comment]
I've already forgotten this problem (4 years) :)
I replaced it with icewm-menu-fdo

**Comment by bbidulock** [comment]
This package is largely deprecated in favor of it's "C"-language replacement: [xde-menu](/bbidulock/xde-menu), which works better than icewm-menu-fdo, particularly in the regard that it can generate fully XDG menuspec compliant menus.

**Comment by bedna-KU** [comment]
@bbidulock I tried to compile xde-menu:
```
xde-menu.c:602:24: error: ‘GMENU_TREE_FLAGS_INCLUDE_UNALLOCATED’ undeclared (first use in this function); did you mean ‘GMENU_TREE_FLAGS_INCLUDE_EXCLUDED’?
  602 |   options.treeflags |= GMENU_TREE_FLAGS_INCLUDE_UNALLOCATED;
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by bedna-KU** [comment]
@bbidulock I tried to compile xde-menu:
xde-menu.c:602:24: error: ‘GMENU_TREE_FLAGS_INCLUDE_UNALLOCATED’ undeclared (first use in this function); did you mean ‘GMENU_TREE_FLAGS_INCLUDE_EXCLUDED’?
  602 |   options.treeflags |= GMENU_TREE_FLAGS_INCLUDE_UNALLOCATED;
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by bbidulock** [comment]
@bedna-KU this is probably the wrong issues list to address this on; however, although the package was configured to allow either libgnome-menu or libgnome-menu-3.0 (both only need glib2), I have only been building with libgnome-menu-3.0 lately.  It looks like a libgnome-menu-3.0 symbol found its way into a libgnome-menu compile path.  Try installing libgnome-menu-3.0 and try again.  Please also report this bug on [xde-menu issues list](/bbidulock/xde-menu/issues).

**Comment by bedna-KU** [comment]
OK, compilation works.

I try:
xde-menu --verbose --menugen --root-menu /home/mario/.icewm/menu --wmname icewm --format icewm

throw error:
xde-menu: E:   xde-menu.c: +3859 : menu_tree_changed() : could not sync menu /home/mario/.icewm/menu

**Comment by bbidulock** [comment]
I think you want:

    --output /home/mario/.icewm/menu

instead of:

    --root-menu /home/mario/.icewm/menu

no?

**Comment by bedna-KU** [comment]
Thanks now work OK.

`xde-menu --menugen --wmname=icewm --format=icewm --root-menu /etc/xdg/menus/xfce-applications.menu --nolaunch --output ~/.icewm/menu`

**Comment by bedna-KU** [comment]
Thanks now work OK.

`xde-menu --menugen --wmname=icewm --format=icewm --root-menu /etc/xdg/menus/xfce-applications.menu --nolaunch --output ~/.icewm/menu`
